name: Build Linux

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt update && \
        sudo apt install -y libgtk-4-dev clang
    - name: Build
      run: |
        swift build --target GtkCodeGen && \
        cd Examples && \
        swift build --target SwiftCrossUI && \
        swift build --target GtkBackend && \
        swift build --target CounterExample && \
        swift build --target ControlsExample && \
        swift build --target RandomNumberGeneratorExample && \
        swift build --target WindowingExample && \
        swift build --target GreetingGeneratorExample && \
        swift build --target NavigationExample && \
        swift build --target SplitExample && \
        swift build --target GtkExample
    # - name: Test
    #   run: swift test
